FROM bitnami/etcd:3

# ENV PROMETHEUS_VERSION=2.0.0

# RUN wget https://github.com/prometheus/prometheus/releases/download/v$PROMETHEUS_VERSION/prometheus-$PROMETHEUS_VERSION.linux-amd64.tar.gz -O /tmp/prometheus-$PROMETHEUS_VERSION.linux-amd64.tar.gz 

# RUN tar -xvzf /tmp/prometheus-$PROMETHEUS_VERSION.linux-amd64.tar.gz --directory /tmp/ --strip-components=1 

# COPY etcd-scraper.yaml /tmp/etcd-scraper.yaml

# COPY etcd.sh /tmp/etcd.sh

# CMD [ "/tmp/etcd.sh" ]