version: '3.4'

services:
  redis:
    image: redis
    privileged: true
    restart: always
    ports: 
      - "6379:6379"
    networks: 
      - app_net

networks:
    app_net:
        external: true