version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks: 
      - app_net

  kafka:
    image:  registry.cn-shenzhen.aliyuncs.com/canbefree/kafka:v1.0.0
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - app_net

networks:
    app_net:
        external: true