version: '3.4'

services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    privileged: true
    restart: always
    ports: 
      - "3000:3000"
    networks: 
      - app_net

    networks: 
      - app_net

networks:
    app_net:
        external: true