version: '3.4'

services:
  mariadb:
    image: mariadb
    privileged: true
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
    ports: 
      - "3306:3306"
    networks: 
      - app_net

networks:
    app_net:
        external: true