global:
  scrape_interval: 10s
  
scrape_configs:
- job_name: etcd
  static_configs:
  - targets: ['etcd-1:2379','etcd-2:2379','etcd-3:2379']

- job_name: mysqld-jk
  static_configs:
  - targets: ['mysqld-exporter:9104']

- job_name: redis_exporter_targets
  static_configs:
  - targets: ["redis://redis-7000:7000","redis://redis-7001:7001","redis://redis-7002:7002"]
  metrics_path: /scrape
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: redis-exporter:9121

- job_name: redis-server
  static_configs:
  - targets: ['redis-exporter:9121']
